const GamePackage = {
    abi: {
	"ABI version": 0,
	"functions": [{
		"name": "constructor",
		"inputs": [
		],
		"outputs": [
		]
	}, {
		"name": "assertIsContractOwner",
		"inputs": [
		],
		"outputs": [
		]
	}, {
		"name": "makeBet",
		"inputs": [
			{"name":"roomId","type":"uint256"}
		],
		"outputs": [
		]
	}, {
		"name": "getBet",
		"inputs": [
			{"name":"playerAddress","type":"uint256"},
			{"name":"roomId","type":"uint256"}
		],
		"outputs": [
			{"name":"value0","type":"uint256"}
		]
	}, {
		"name": "givePrize",
		"inputs": [
			{"name":"winner","type":"uint256"},
			{"name":"prizeSize","type":"uint256"}
		],
		"outputs": [
		]
	}, {
		"name": "withdrawPrize",
		"inputs": [
		],
		"outputs": [
		]
	}, {
		"name": "refundBet",
		"inputs": [
			{"name":"playerAddress","type":"uint256"},
			{"name":"roomId","type":"uint256"}
		],
		"outputs": [
		]
	}, {
		"name": "withdrawRefund",
		"inputs": [
		],
		"outputs": [
		]
	}]
},
    imageBase64: 'te6ccgECaQEADGIAAgE0BgEBAcACAgPPIAUDAQHeBAAD0CAAQdgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAF+/wD4AIn0BSHDAY4VgCD+/gFzZWxlY3Rvcl9qbXBfMPSgjhuAIPQN8rSAIP78AXNlbGVjdG9yX2ptcPSh8jPiBwEBwAgCASAKCQDM//79AW1haW5fZXh0ZXJuYWwjIyOCEAbisn3wATQQIxIBI4IQ+uB4TfABJCDHApLUNt8wghANBR5z8AExMSDHAY4Z/vwBbXNnX2lzX2VtcHR5MG3I9ADJ7VTbMODTBwHyd9MfAfABAgLeaAsBATAMAgEgLA0CASAfDgIBIBYPAgEgExACAVgSEQAftGY/MhhBCGfWdeP4AO2YQACltXA8Jv9/ALOyui+2ubOvuDqxNbK8uBDjgUs4GJi47ZhHFJDqkGOAy7gCL4I47ZhwEECBAEEILNhISngAmZD8gJAREvyIEHlUL4I4cW4QGJjtmEACASAVFAA5tzc1Qn++wFnZXRfYmFsYW5jZe1HbxBvF28Q2zCAAH7eMgt9MIIQrQO2a/AB2zCACASAaFwIBIBkYAHO2QI9Xv77AWVuY29kZWdyYW1zIHC9jhYgtgN3oHipBCAjywMzISMieKjPATMwlXAiywMy4iExMdswgAKG3Gkemf7+AWNoYW5nZV9hcnJfbGVuIYAg9I6SMaSRcOIgIr6OFI4RICK8syDcMKUgI4Ag9FswM3DmnyNus5ojInGhJIAg9BYz3uIiBF8E2zCACASAeGwIBbh0cAEOxWdePBCCjvMaf4ALh2omh6AsCAgHoHSen/6Mi4cV15cDJACWxd6JJp/+n/mEEIT3q2F/gA7ZhALe317PkYIQJt4EePABcLzy4GRx7UTQ9AWBAQD0a4IQUd5jT/ABAVMQgQEA9GsjAYIQJt4EePAByMv/ydBZgQEA9BZZgQEA9G8wce1E0PQFgQEA9G8wyPQAye1UMIAIBICcgAgEgJCECAWIjIgAmsu4x+NP/0/8wghAGIyQH8AHbMACQstOrTSHXSSAivp0iItcBNCAkVTFfBNsw4CIh1xg0I9Q1JNFtNSDQICUlodcYMsgkIc4xISHOMSDJ0DEgJ9cBMiAkVYFfCdswAgJ2JiUAw7AHbNcEIKO8xp/gAufaiaHoCwICAejXAgIB6B0np/+jIuHFBCCjvMaf4ALj2omh6AsCAgHo1wICAejXAgIB6B0np/+jIuHEQOF55cDIQQQgo7zGn+ADkZOhBCCrfnk94AJhAB2xAhTaYQQgdxDRceADtmECASArKAICdyopAFuwwq0j/fgC5srcyL7K8Oi+2ubP8EsEIRAsD3vgAkRERQQgy//Rz+ACQOH2AL4JAI+x6thfBCGfWdeP4ALl2omh6AsCAgHo1kQCpiECAgHoHSen/6Mi4cRHQZGX/5OgswICAegs5dqJoegLAgIB6N5hkegBk9qovgUAGbkCwPe9qO3iDeMbZhACASBNLQIBID8uAgEgNy8CASAzMAIBIDIxAJ20qcqz/34AubowuTopsrcyJrmz5DkQ5YCYuBDlgBi4EOWDmJEQ5f+YkGToGMEIRAsD3vgA/BGSkLg4OBQUFDi4QQg6R1kzeACQOH2AL4RAAB+0zmuemEEIFoCxX3gA7ZhAAgN6YDU0AHutD3EDxkEUAQekdJGNJIuHE4RxAQEVzZkG4YEZCTQBB6B0iYy+Q4AWeA5OhxEBJnGhhSOHMYEOToAi+CbZhAHrrHWTN/fACxOrS2Mja5s+Q4EOWAGJCQ5YAYkRDlgBi4EOWAGJGQ5xiSEOcYkBNBCGyBHq94AJi4EOWAGJATwQhsgR6veACYkBRBCGyBHq94AJiUEOWfmJSQ5Y+YuBDlgBiQZ5qV66S40BCQ3ky4EeWAGZYR5xnDYANI4QcSPLADPILSHOMSDJJMw0MOIiyQ1fDdswAgEgOzgCASA6OQBRtV+k2P9+gLOyui+5srYzL7CyMjlBCEQLA974AMAFwQgs2EhKeADtmEAAMbUJaFU4dqO3iOh6Arx6B0np/+jIuHFtmEACAWo9PADBsf/Rz/36AsTq0tjIvsrw6L7a5s+Q5kOWAmJCQ5xi4EOWAmJEQ5Z+YuBDlj5i4EOWAGJBnmpJrpLjQEJDeTLgR5YAZkpHnGccIOJHlgBnkExDnGJBkkmYaGHERZIMvg22YQEHsTHHFz4A/v7+AWVuY29kZV9hcnJheV9yjmUgIrmzINwwJCPPPY4k/v8BZW5jb2RlX2FycmF5X3IwICSAIPQO8uBkICbONiGkMjBwjib+/wFlbmNvZGVfYXJyYXlfcjHIJCQkJIIQZJjji/ABySAmzDYwcuIgcrqSMH/g8tBjcOYkBV8F2zACASBJQAIBIEZBAgEgRUICAnNEQwBJrBDOL/fwC5srcyL7S3Oi+2ubOvmTgQkcCTiEEIPqnKs/gAr4FABdrCY2bp/+n/mEEICnJLjHgA5DhnhYPBCC7CY2bnhY+Q54X/5OhBCE+wq0j4AO2YQAJ7TYSEoQkOuQkGn/mRiQAa+B7ZhAAgEgSEcAP7Tfnk9/fQC5srcyL7O5MLa5uBCRksEIPqnKs/gAr4HAADG07zGnuPajt4joegK8egdJ6f/oyLhxbZhAAgFIS0oAI7V6uWvp/5hBCGOvZ8j4AO2YQAHztcw/VTaROUEIWGnVpvgAkBqQuF1HMZJqG2g4RyyQ66SQE99PkRPrjBoQEZRAEHoLG5g4RxmQOF1PkWulOF1JGDlIuHEQbhg4SLhxEG4YERCUEdDBCAY4DIl4AJCSFMAQegscEBqvgThxEDldSRg/8HloMZhSOHMYGEBMALaOUCFyuo5FJNMHNnCOOyAiubMg3DAm10kgJ76eJyfXGDkgIyiAIPQWNzCOGSchKCOhghAMcBkS8AEhJCmAIPQWOCA6XwLiMKRw5jAwlHDy4GTi4iIlVUFfBdswAgEgV04CASBSTwIBalFQAFKziGi4bcj0AMntVIIQUd5jT/AByMv/ydBw7UTQ9AWBAQD0Fsj0AMntVAA4sxHn9MglISPPATEgydAxICUlJfQWNCMGXwbbMAIBIFZTAgFqVVQAe7ACxX0EIKO8xp/gAuXaiaHoCwICAejXAgIB6B0np/+jIuHEQOF55cDIQQQgo7zGn+ADkZOhBCCrfnk94AJhADewXBYB/foCzsrovuTC3Mi+5srKydqO3iDeLbZhADG3t4EeHLtR28R0PQFePQOk9P/0ZFw4tswgAgEgX1gCASBcWQEJtsIJzyBaAf7+/AFlbmNvZGVfYXJyYXkhgCD0jpIxpJFw4iBwuo4QciTLATQgJMsHNCMEXwTbMOAjzzVyeKAiJKigvo4v/v4BZW5jb2RlX2FycmF5MDFyJMsBNCAkywc0IyMjI3CCEGSY44vwATQjBF8E2zDgcCTLATTIIyMjcIIQZJjji/ABWwA4ySTMNP7/AWVuY29kZV9hcnJheV9vayMEXwTbMAIBIF5dAE20ckuMEBE49qJoegLAgIB6NcCAgHo1wICAegdJ6f/oyLhxGJjtmEAAkbSm+0UQ66SQEV9OkRFrgBoQEiqYr4JtmHAREOuMGhHqGpJotpqQaBASktDrjBlkEhDnGJCQ5xiQZOgYkBPrgBkQEirAr4TtmEACASBlYAIBamRhAQewCjznYgH4/v8Bc3RvcmVfc2lnbmF0dXJlbSFwIniBAQCCEDkR5/TwATEicSJ4gQEAghA5Eef08AExI3IieIEBAIIQORHn9PABMSRzIniBAQCCEDkR5/TwATGCECwuCwDwAYIQ7NzVCfAByCEhy38xIMnQMYIQbr9JsfABIHQmeIEBAGMAaoIQORHn9PABNSF1Jnj0FjUjdiZ4gQEAghA5Eef08AE1yCUh9AAxIMkx7UcgIm+MMSDtV18LAFWw4DIkREWuMGhHqGpJotpqQaBqSEeuMG2QRkOcYkJDnGJBk6BOqsK+D7ZhAgJ2Z2YAca+Kyff78AWdldF9zcmNfYWRkciDQINMAMiBwvZZwA18D2zDgIXPXITIhgAuCEFmwkJTwAQNfA9swgBxroyQHghDPrOvH8AFz7UTQ9AWBAQD0ayIBIsjL/8nQWYEBAPQWc+1E0PQFgQEA9G8wyPQAye1UXwKAHc/v0BbWFpbl9pbnRlcm5hbCMjI4IQBuKyffABNBAjEgFwghANBR5z8AExMSDHANzTBwHyd9MfAfAB2zCA='
};

module.exports = GamePackage;
